// Artikel-Daten für die Schülerzeitung

// title = titel des Artikels
// authors = array mit autoren
// type = art des artikels (bericht, interview, rezept, etc.)
const articles = [
  {id:1,day:'donnerstag',
    title:'Rentner: Was hat sich in Fehraltorf verändert?',
    authors:['Almir','Noah'],
    type:'Bericht',
    excerpt:'Ein Blick auf Veränderungen im Dorf — von Läden bis zum Bahnhof.',
    content:'<p>Interview mit Bewohnern und Vergleich: Was hat sich in den letzten 10 Jahren verändert? ... (Platzhalter)</p>'},
  {id:2,day:'donnerstag',
    title:'Musik-Umfrage',
    authors:['Lara','Viola','Livia'],
    type:'Umfrage',
    excerpt:'Was hören Schülerinnen und Schüler 2025 am liebsten.',content:'<p>Die Ergebnisse unserer Musik-Umfrage: Pop, Rap, Rock — und überraschende Geheimtipps.</p>'},
  {id:3,day:'donnerstag',
    title:'Hunderassen, Vergleich (Englisch)',
    authors:['Lilly'],
    type:'Image',
    excerpt:'A comparison of popular dog breeds — strengths & needs.',
    content:`<div style="display:flex;justify-content:center;">
    <img src="./assets/similar looking dog breeds.png" alt="Your Browser cant render images, Im sorry" style="max-width:100%;height:auto;">
  </div>`},
  {id:4,day:'donnerstag',
    title:'Essen in verschiedenen Ländern',
    authors:['Leyna','Kirana'],
    type:'Bericht',
    excerpt:'Rezepte, Traditionen und Geschmack: eine kulinarische Tour.',
    content:'<p>Wir probieren Gerichte aus Albanien, Mexiko, Japan und mehr. Interviews mit Schülern, die Rezepte mitbrachten.</p>'},
  {id:5,day:'donnerstag',
    title:'5 Top-Reiseziele',
    authors:['Sarah','Liv','Jennifer'],
    type:'Bericht',
    excerpt:'Die fünf schönsten Reiseziele für 2025 — Budgetfreundlich.',
    content:'<ol><li>Albanien — Strände & Natur</li><li>Portugal — Städte & Küste</li></ol>'},
  {id:6,day:'donnerstag',
    title:'Albanien — Länderporträt',
    authors:['Altin','Ekrem',],
    type:'Porträt',
    excerpt:'Geschichte, Kultur und Highlights Albaniens.',content:'<p>Albanien: eine kompakte Einführung — Kultur, Küche und Top-Sehenswürdigkeiten.</p>'},
  {id:7,day:'donnerstag',
    title:'AC/DC',
    authors:['Lowen','Kilian', 'Melvin'],type:'Bericht',excerpt:'Bandporträt: Legendenstatus und Einfluss.',content:'<p>Kurzporträt zur Band AC/DC: Wichtige Alben und Einfluss auf die Rockmusik.</p>'},
  {id:8,day:'donnerstag',
      title:'Schülerinterview: Leon',authors:['Leano', 'Noah R.'],type:'Interview',
      excerpt:'Ein Porträt über Leon und seine Hobbys.',content:'<p>Leon erzählt: Lieblingsfächer, Hobbys, und ein verrücktes Schulereignis.</p>'},
  {id:9,day:'donnerstag',
    title:'Jahr 2025: Was ist passiert?',
    authors:['Noah M.'],
    type:'Bericht',
    excerpt:'Eine Übersicht über wichtige Ereignisse 2025.',content:'<p>Was passierte lokal und international in 2025? Kurzüberblick für die Schule.</p>'},
  {id:10,day:'montag',
    title:'Aussergewöhnliche Hobbys',
    authors:['Jana','Gwendolyn','Max'],
    type:'Porträt',
    excerpt:'Schülerinnen mit Hobbies, die überraschen.',content:'<p>Vom Urban Gardening bis Parkour — diese Hobbies kennst du noch nicht.</p>'},
  {id:11,day:'montag',
    title:'Allgemeinwissen',
    authors:['Helena','Elzana'],
    type:'Quiz',
    excerpt:'Kurzes Quiz: Teste dein Allgemeinwissen!',content:'<p>Frage 1: ...</p>'},
  { id:12,day:'montag',
  title:'Tacos-Test',
  authors:['Zaron','Nemanja','Niklas'],
  type:'Video',
  excerpt:'Welcher Taco schmeckt am besten?',
  content: `<video src="./assets/Taco-Test.mp4" controls class="modal-video"></video>`
},
  {id:13,day:'montag',
    title:'Fake Marken',authors:['Leon'],
    type:'Bericht',
    excerpt:'Wie erkenne ich Fake-Marken?',
    content:'<p>Tipps gegen Fakes und wie man Qualität prüft.</p>'},
  {id:14,day:'montag',
    title:'Rezept: Trilece',authors:['Esma'],
    type:'Rezept',
    excerpt:'Ein klassisches Milchkuchen-Rezept (albanisch-türkische Wurzeln).',
    content:'<p>Zutaten und Schritt-für-Schritt Anleitung für Trilece.</p>'},
  {id:15,day:'montag',
    title:'Rezept: kalorienarmer Kuchen',authors:['Elea','Lara'],type:'Rezept',
    excerpt:'Lecker & leicht — Backen ohne schlechtes Gewissen.',content:'<p>Backtipp: Ersatz für Zucker & Fett, Backzeit und Tipps.</p>'},
  {id:16,day:'montag',
    title:'Fussball-Trick Tutorial',authors:['Leandro','Simao', 'Maurin'],
    type:'Tutorial',
    excerpt:'Lerne einen coolen Trick in 5 Schritten.',content:'<p>Video-Anleitung und Schritt-für-Schritt-Bilder.</p>'},
  {id:17,day:'montag',title:'KI-Video',authors:['Tobias', 'Levin'],
    type:'Video',
    excerpt:'Ein experimentelles Video mit KI-Effekten.',content:'<p>Wie wir KI-Tools genutzt haben, um ein Schulvideo zu erstellen.</p>'},
  {id:18,day:'montag',title:'Lieblingssport — Umfrage',authors:['Danis','Elio','Elvis'],type:'Umfrage',excerpt:'Was ist der beliebteste Sport an unserer Schule?',content:'<p>Ergebnisse und kurze Porträts der beliebtesten Sportarten.</p>'},
  {id:19,day:'montag',title:'Porträt von Personen',authors:['Aryen','Dionne'],type:'Porträt',excerpt:'Kurze Porträts von spannenden Persönlichkeiten.',content:'<p>Interviews und Hintergründe.</p>'},
  {id:20,day:'montag',title:'Allgemeines über Schule',authors:['Luana','Lena','Ellaine'],type:'Bericht',excerpt:'Aktuelles aus dem Schulalltag.',content:'<p>Neuigkeiten: Regeln, Mensa, Events.</p>'},
  {id:21,day:'montag',title:'Reisen im Sommer und Winter',authors:['Dino','Almin','Berkay'],type:'Bericht',excerpt:'Tipps für Sommer- und Winterferien.',content:'<p>Packlisten, Budgettipps und sichere Ziele.</p>'},
  {id:22,day:'montag',title:'Tiktok: schädlich?',authors:['Anastasia','Annika'],type:'Bericht',excerpt:'Diskussion über Risiken und Chancen.',content:'<p>Datenschutz, Suchtgefahr und kreative Möglichkeiten.</p>'},
  {id:23,day:'montag',title:'Handy — Bericht',authors:['Daniele','Flamur'],type:'Bericht',excerpt:'Wie Handynutzung unseren Alltag beeinflusst.',content:'<p>Statistiken, Tipps für gesunden Gebrauch.</p>'},
  {id:24,day:'montag',title:'Sucht — Bericht',authors:['Dario','Davide','Argjend'],type:'Bericht',excerpt:'Umgang mit Sucht & Hilfsangebote.',content:'<p>Wichtige Anlaufstellen und Tipps.</p>'},
  {id:25,day:'montag',title:'Lieblingsgericht/Essen (Video)',authors:['Mayla','Dafina'],type:'Video',excerpt:'Schüler zeigen ihre Lieblingsgerichte.',content:'<p>Kurze Clips mit Rezeptideen.</p>'},
  {id:26,day:'montag',title:'Umfrage Abschlussfest 3. Sek',authors:[],type:'Umfrage',excerpt:'Was wünscht ihr euch fürs Abschlussfest?',content:'<p>Ergebnisse und Vorschläge des Jahrgangs.</p>'},

  {id:27,day:'donnerstag',
    title:'Cute Animals',authors:['Lilly'],
    type:'Image',
    excerpt:'Bonus article with cute animal pictures.',
    content:'<img src="./assets/cute_animals.png" alt="Your Browser cant render images, Im sorry" style="max-width:100%;height:auto">'},
];
