// Artikel-Daten für die Schülerzeitung

// title = titel des Artikels
// authors = array mit autoren
// type = art des artikels (bericht, interview, rezept, etc.)
const articles = [
  {id:1,
    title:'Paper Dart',
    authors:['Almir','Noah'],
    type:'Bericht',
    excerpt:'',
    content:'<p>Interview mit Bewohnern und Vergleich: Was hat sich in den letzten 10 Jahren verändert? ... (Platzhalter)</p>'},
  {id:2,day:'donnerstag',
    title:'Musik-Umfrage',
    authors:['Lara','Viola','Livia'],
    type:'Umfrage',
    excerpt:'Was hören Schülerinnen und Schüler 2025 am liebsten.',content:'<iframe src="./assets/Musikumfrage an unserer Schule 1.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe>'},
  {id:3,day:'donnerstag',
    title:'Hunderassen, Vergleich (Englisch)',
    authors:['Lilly'],
    type:'Image',
    excerpt:'A comparison of popular dog breeds — strengths & needs.',
    content:`<div style="display:flex;justify-content:center;">
    <img src="./assets/similar looking dog breeds.png" alt="Your Browser cant render images, Im sorry" style="max-width:100%;height:auto;">
  </div>`},
  {id:4,day:'donnerstag',
    title:'Essen in Vietnam',
    authors:['Leyna','Kirana'],
    type:'Bericht',
    excerpt:'Rezepte, Traditionen und Geschmack: eine kulinarische Tour.',
    content:'<div class="video-container"><video src="./assets/Essen in Vietnam.mov" controls class="responsive-video"></video><iframe src="./assets/Vietnam.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},
  {id:5,day:'donnerstag',
    title:'2 Top-Reiseziele',
    authors:['Sarah','Liv','Jennifer'],
    type:'Bericht',
    excerpt:'Die zwei beliebtesten Reiseziele für 2026.',
    content:'<div><img src="./assets/zwei beliebte Reiseziele.png" alt="Your Browsercant render Images. Im sorry" style="max-width:100%;height:auto"></div>'},
  {id:6,day:'donnerstag',
    title:'Albanien — Länderporträt',
    authors:['Altin','Ekrem',],
    type:'Porträt',
    excerpt:'Geschichte, Kultur und Highlights Albaniens.',content:'<iframe src="./assets/Albanien.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe>'},
  {id:7,day:'donnerstag',
    title:'AC/DC',
    authors:['Lowen','Kilian', 'Melvin'],type:'Bericht',excerpt:'Bandporträt: Legendenstatus und Einfluss.',content:'<iframe src="./assets/AC DC.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe>'},
  {id:8,day:'donnerstag',
      title:'Schülerinterview: Leon',authors:['Leano', 'Noah R.'],type:'Interview',
      excerpt:'Ein Porträt über Leon und seine Hobbys.',content:'<audio id="audio-leon" src="./assets/Schülerinterview mit Leon.mp3" controls controlsList="nodownload" preload="metadata"></audio>'},
  {id:9,day:'donnerstag',
    title:'Beliebte Konzerte 2025',
    authors:['Noah M.'],
    type:'Bericht',
    excerpt:'Eine Übersicht der beliebtesten Konzerte 2025.',content:'<iframe src="./assets/Beliebte Konzerte 2025.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe>'},
  {id:10,day:'montag',
    title:'Aussergewöhnliche Hobbys',
    authors:['Jana','Gwendolyn','Max'],
    type:'Porträt',
    excerpt:'Leute mit Hobbies, die überraschen.',content:'<div><iframe src="./assets/Aussergewöhnliche Hobbys.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},
  {id:11,day:'montag',
    title:'Allgemeinwissen',
    authors:['Helena','Elzana'],
    type:'Quiz',
    excerpt:'Kurzes Quiz: Teste dein Allgemeinwissen!',content:'<p>Frage 1: ...</p>'},
  { id:12,day:'montag',
  title:'Tacos-Test',
  authors:['Zaron','Nemanja','Niklas'],
  type:'Video',
  excerpt:'Welcher Taco schmeckt am besten?',
  content: `<video src="./assets/Taco-Test.mp4" controls class="modal-video"></video>`
},
  {id:13,day:'montag',
    title:'Fake Marken',authors:['Leon', 'Nils'],
    type:'Bericht',
    excerpt:'Wie erkenne ich Fake-Marken?',
    content:'<div style="display:flex;justify-content:center;"><img src="./assets/Interview Replicas.png" alt="Your Browser cant render images, Im sorry" style="max-width:100%;height:auto;"></div>'},
  {id:14,day:'montag',
    title:'Rezept: Pite mit Käse',authors:['Esma'],
    type:'Rezept',
    excerpt:'Ein traditionelles türkisches Gericht mit Fladenbrot.',
    content:'<div style="display:flex;justify-content:center;"><img src="./assets/Rezept_Trilece.png" alt="Your Browser cant render images, Im sorry" style="max-width:100%;height:auto;"></div>'},
  {id:15,day:'montag',
    title:'Rezept: kalorienarmer Käsekuchen',authors:['Elea','Lara'],type:'Rezept',
    excerpt:'Lecker & leicht — Backen ohne schlechtes Gewissen.',content:'<iframe src="./assets/White Modern Recipe Card.pdf" width="100%" height="600"></iframe>'},
  {id:16,day:'montag',
    title:'Fussball-Trick Tutorial',authors:['Leandro','Simao', 'Maurin'],
    type:'Tutorial',
    excerpt:'Lerne einen coolen Trick in 5 Schritten.',content:'<video src="./assets/Fussballtrick.mp4" controls class="modal-pvideo"></video>'},
  {id:17,day:'montag',title:'KI-Video',authors:['Tobias', 'Levin'],
    type:'Video',
    excerpt:'Ein experimentelles KI-Video mit einem kleinen Bericht.',content:'<div><video src="./assets/Generated video 1.mp4" controls class="modal-video"></video><video src="./assets/Wie ich enstehe.mp4" controls class="modal-video"></video><video src="./assets/Video Küche.mp4" controls class="modal-video"></video><iframe src="./assets/KI.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},
 
 
    {id:18,day:'montag',title:'Umfrage Hobbys',authors:['Danis','Elio','Elvis'],type:'Umfrage',
      excerpt:'Was für Hobbys machen die Schüler an unserer Schule?',content:'<iframe src="./assets/Hobbys diagramm .pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe>'},
 
 
  {id:19,day:'montag',title:'Umfrage zur Schule',authors:['Aryen','Dionne'],type:'Porträt',excerpt:'Umfrage zu unserer Schule',content:'<iframe src="./assets/Schülerzeitung Umfrage zur Schule DD_AK.pdf" width="100%" height="600"></iframe>'},
  
{id:20,day:'montag',
  title:'Stock-Test',
  authors:['Nils','Leon',],
  type:'Bericht',excerpt:'Welcher Stock ist der beste?',
  content:'<video src="./assets/Stock Test.mp4" controls class="modal-video"></video>'},


  {id:21,day:'montag',title:'Reisen im Sommer und Winter',authors:['Ellaine','Lena','Luana'],type:'Bericht',excerpt:'Tipps für Sommer- und Winterferien.',content:'<div><iframe src="./assets/Reisen_im_Winter.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe><iframe src="./assets/Reisen im Sommer.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},
  
  {id:22,day:'montag',title:'Tiktok: schädlich?',authors:['Dino','Almin', 'Berkay'],type:'Bericht',excerpt:'Diskussion über Risiken und Chancen.',content:'<div><iframe src="./assets/TikTok.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},
  {id:23,day:'montag',title:'Sucht',authors:['Daniele','Flamur'],type:'Bericht',excerpt:'Eine Präsentation über Sucht.',content:'<div> <iframe src="./assets/Drogen.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},

  {id:24,day:'-',title:'Gazakrieg',authors:['Noah M'],type:'Text',excerpt:'Bericht über den Gazakrieg.',content:'<div><iframe src="./assets/Gaza Krieg (1).pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},

  {id:26,day:'montag',title:'Umfrage Abschlussfest 3. Sek',authors:['Mayla', 'Dafina'],type:'Umfrage',excerpt:'Was wünscht ihr euch fürs Abschlussfest?',content:'<div><iframe src="./assets/Abschlussfest.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},

  {id:27,day:'donnerstag',
    title:'Cute Animals',authors:['Lilly'],
    type:'Image',
    excerpt:'Bonus article with cute animal pictures.',
    content:'<img src="./assets/cute_animals.png" alt="Your Browser cant render images, Im sorry" style="max-width:100%;height:auto">'},

  {id:28,day:'-',
    title:'Lehrerbewertung',authors:['Gwendolin','Jana','Max'],
    type:'Text',
    excerpt:'Lehrerbewertung der 3. Sek.',
    content:'<div><iframe src="./assets/Lehrerbewertung.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},

  {id:29,day:'-',
    title:'Rätselecke',authors:['Emilie','Frau Breitenmoser',],
    type:'Bericht',
    excerpt:' Rätsel der Rätselecke zum selber knobeln.',
    content:'<div><iframe src="./assets/Rätselecke.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},

  {id:30,day:'-',
    title:'Handy',authors:['Anastasia','Annika',],
    type:'Bericht',
    excerpt:' Handyanalyse.',
    content:'<div><iframe src="./assets/Handy.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},

    {id:30,day:'-',
    title:'Lieblingsgericht einer Lehrperson',authors:['Dario','Argjend', 'Davide'],
    type:'Bericht',
    excerpt:'Das Lieblingsgericht einer Lehrperson nachkochen.',
    content:'<div><iframe src="./assets/Handy.pdf" alt="Your Browser cant render images, Im sorry" width="100%" height="600"></iframe></div>'},
];
